### ISSUE TITLE
Support for PettingZoo?

### ISSUE THREAD

**Issue by Phoenix-surgere** [uoe-agents/epymarl#12]
Hi, 

I would like to ask, are there any plans to make this library compatible with PettingZoo? I've read the overview and docs but I can't seem to find any reference to that at all, and it's a shame since PZ would work extremely well (in principle) with another dedicated MARL library.

**Comment by semitable** [comment]
AFAIK, cooperative MARL has the same interface as OpenAI's Gym (which is the bigger project here). You can easily define a tuple of observations (one tuple element for each agent), actions, etc - and a single reward (because it's cooperative). That's identical to Gym. I don't see the reason for supporting a redundant API but we will be happy to merge a wrapper if someone wants to contribute it.

**Comment by Phoenix-surgere** [comment]
I do not believe that supporting easy interdependency with PettingZoo, one of the most well-supported libraries for MARL environments "redundant". Requiring potential users to dabble in low-level environment manipulation to conform to a Gym specification and not having comprehensive documentation is problematic for wider adoption, in my view.

**Comment by LukasSchaefer** [comment]
Hi! Sorry for the late follow-up.

There have been several difficulties of an improved integration of PettingZoo due to backwards incompatible changes introduced in later `gym` and more recently `gymnasium` versions which PettingZoo relies and that were not compatible with EPyMARL and several of our environments that relies on the outdated `gym==0.21` version.

That being said, I am very glad that we just published a big update to EPyMARL including lots of new features and a move to `gymnasium` from `gym` (as well as support for training in non-common-reward games, weights and biases logging, and more)! As part of this move to `gymnasium`, we could now easily integrate PettingZoo environments. I have tested it with MPE environments of PettingZoo as well as some simpler environments and it seems to work well. Note, that continuous control tasks will not be supported.

I will close this issue since PettingZoo integration now works, but please let us know if there are any outstanding issues!
