### ISSUE TITLE
Weird, a2c and ppo learner has a target critic network

### ISSUE THREAD

**Issue by Theohhhu** [uoe-agents/epymarl#17]
Why is there a target network in A2C / MAA2C / PPO / MAPPO implementation? 
Till now I haven't find any target network used in previous works like MAPPO's original implementation. 
Is there any explanation?

**Comment by semitable** [comment]
Hi @Theohhhu 

What original implementation of MA-PPO are you referring to? As far as I know, this algorithm would trace back to MA-DDPG (it's of course just a direct re-application of the MA-DDPG principles to another algorithm).

As per the target network: we have found that it increases stability even on on-policy algorithms. Since it does work, we decided to make the comparison with off-policy algorithms (that do use a target network) a bit fairer. You should be able to easily disable it if target networks don't work as well in your environments.

**Comment by Theohhhu** [comment]
Thanks for your explanation. Still, I believe there is no need for a target critic in on policy RL methods. Only off policy need one, like MADDPG as you mentioned. Please refer to https://github.com/marlbenchmark/on-policy/tree/main/onpolicy and https://github.com/decisionforce/CoPO.

I guess the **stability even on on-policy algorithms** comes from your **q_nstep** in computing the target critic value. However, this is not a standard way to compute target critic value in on policy RL methods, but a common way in off policy RL.

I mean there is nothing wrong if you use a **q_nstep** in TD error, but on policy methods usually do not use that, as it will introduce overestimation on critic value (and that is why we use target network in off policy RL). And the optimization on the critic network is then not a standard regression anymore if **q_nstep** exists in TD error.

**Comment by semitable** [comment]
Hi @Theohhhu 

Just to clarify, we did not base our implementation on the papers you mention (or any for MA-PPO for that matter). For example, the papers you link are dated later (2021, and I think one isn't even published?) than our original implementations for this paper. We consider MA-PPO a simple application of the ideas behind MA-DDPG by Lowe et al to the PPO algorithm. Therefore, not a very original idea in the first place.

Second, as I explained, we decided to add a target network because it works well. There is no argument here for us: if it works better than not including it, then it's worth including it. You are free to disable it in your own experiments if you so desire. The target network is just a simple idea that goes back to the early deep RL papers and again, we do not consider it an important element (other than just another trick to increase performance).

Finally, you are inaccurate in saying that the target network is meant to address the "overestimation" of the critic value. This was the idea behind Double DQN (and others): but not the original use of a critic network in the original DQN paper. The target network was originally used to address the "moving target" problem by offering a more stable target. Creating a stable target was the reason we gave it a go in the first place (remember that in multi-agent settings, values are often more volatile which is quite possibly the reason we observed performance gains).

Hopefully, that answers your question and gives an idea of our reasoning.

Best,
