### ISSUE TITLE
Choosing runner: "parallel" in maddpg_ns.yaml causes error.

### ISSUE THREAD

**Issue by xiaobanni** [uoe-agents/epymarl#27]
Setting  `runner: "parallel"` in `maddag_ns.yaml` causes error:

`TypeError: select_actions() got an unexpected keyword argument 'bs'`

Thanks for this impactful work. I look forward to your reply and thank you in advance.

**Comment by Nabzozifo** [comment]
I encountered the same error. This is due to the fact that in the `maddpg_controller` the function select action has no argument `bs`. You can solve this by adding `bs=""` or `bs=None` in the function `select_actions()` in the file `contollers/maddpg_controllers.py`line `61`.  Replace ` def select_actions(self, ep_batch, t_ep, t_env=0, test_mode=False):` by ` def select_actions(self, ep_batch, t_ep, bs="", t_env=0, test_mode=False):`. Another solution is to verify is the created `mac` is an instance of `maddpmac` in `parallel_runner.py` file and your call the right function without the `bs` argument.
