### ISSUE TITLE
AttributeError: Has no attribute 'unit_dim'

### ISSUE THREAD

**Issue by Skylarking** [uoe-agents/epymarl#33]
In the environment LBF, it raise this error. I want to know the meaning of 'unit_dim'.

**Comment by LukasSchaefer** [comment]
Hi, sorry for the very late response.

It seems your issue is unrelated to EPyMARL but instead an issue with the LBF environment. Please check the [LBF environment repo](https://github.com/semitable/lb-foraging) where we have recently pushed an update which might resolve your issue. If your issue is not addressed already, please raise an issue in that repository. Thanks!
