### ISSUE TITLE
SMAC environment problem 

### ISSUE THREAD

**Issue by abdulghani91** [uoe-agents/epymarl#45]
I'm trying to run MAPPO or IPPO with sc2 environment but I couldn't figured out how to specify the maps.
I already us pymarl and run the algorithms with this code:

python3 src/main.py --config=qmix --env-config=sc2 with env_args.map_name=2s3z

I want to run epymarl with MAPPO or IPPO algorithms with the same map 2s3z from sc2. could any one help me with that?
I'm using this code:

python3.7 src/main.py --config=mappo --env-config=sc2 with env_args.time_limit=25 env_args.key="SMAC:2s3z"

I get this error:

sacred.utils.ConfigAddedError: Added new config entry that is not used anywhere
Conflicting configuration values:
env_args.key=SMAC:2s3z

**Comment by papoudakis** [comment]
There are two issues with the command that you are using. First, in SMAC you do not have to specify the timelimit because this is set by the map. Second you do not have to add the "SMAC" keyword before the map_name. 
The correct command is:
```
python3.7 src/main.py --config=mappo --env-config=sc2 with env_args.map_name="2s3z"
```
which is the same as the command you have to use in PyMARL.

**Comment by abdulghani91** [comment]
@papoudakis I already try this command and I try it again.

`python3.7 src/main.py --config=mappo --env-config=sc2 with env_args.map_name="2s3z"`

I got this error:

[DEBUG 15:56:57] pymarl Stopping Heartbeat
[ERROR 15:56:57] pymarl Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "src/main.py", line 36, in my_main
    run(_run, config, _log)
  File "/media/abdulghani/APPS/AI Safety/MultiAgents RL/Algorithms/epymarl/src/run.py", line 49, in run
    logger.setup_tb(tb_exp_direc)
  File "/media/abdulghani/APPS/AI Safety/MultiAgents RL/Algorithms/epymarl/src/utils/logging.py", line 18, in setup_tb
    configure(directory_name)
  File "/home/abdulghani/.local/lib/python3.7/site-packages/tensorboard_logger/tensorboard_logger.py", line 296, in configure
    _default_logger = Logger(logdir, flush_secs=flush_secs)
  File "/home/abdulghani/.local/lib/python3.7/site-packages/tensorboard_logger/tensorboard_logger.py", line 46, in __init__
    os.makedirs(self.logdir)
  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: '/media/abdulghani/APPS/AI Safety/MultiAgents RL/Algorithms/epymarl/results/tb_logs/mappo_seed950075212_2s3z_2023-03-20 15:56:57.983744'

**Comment by abdulghani91** [comment]
@semitable did I have to copy the content to the home folder
i am using 
Ubuntu: 20.04
python: 3.7.13
Tensorboard: 2.11.2

**Comment by abdulghani91** [comment]
this is a list for all packages that I have installed

absl-py==1.4.0
atomicwrites==1.4.1
attrs==22.2.0
cachetools==5.3.0
certifi==2022.12.7
chardet==3.0.4
charset-normalizer==3.1.0
cloudpickle==2.2.1
colorama==0.4.6
cycler==0.11.0
deepdiff==6.3.0
docopt==0.6.2
entrypoints==0.4
enum34==1.1.10
fonttools==4.38.0
future==0.18.3
gitdb==4.0.10
GitPython==3.1.31
google-auth==2.16.2
google-auth-oauthlib==0.4.6
grpcio==1.51.3
gym==0.21.0
idna==2.7
imageio==2.26.0
importlib-metadata==4.13.0
jsonpickle==1.5.2
kiwisolver==1.4.4
lbforaging==1.1.1
Markdown==3.4.1
MarkupSafe==2.1.2
matplotlib==3.5.3
mock==5.0.1
more-itertools==9.1.0
-e git+https://github.com/semitable/multiagent-particle-envs.git@2cef12f72a9192a819ef289646526801c39fb909#egg=mpe
mpyq==0.2.5
munch==2.5.0
networkx==2.6.3
numpy==1.21.6
numpy-stl==3.0.1
oauthlib==3.2.2
ordered-set==4.1.0
packaging==23.0
pbr==4.3.0
Pillow==9.4.0
pluggy==0.7.1
portpicker==1.2.0
probscale==0.2.5
protobuf==3.19.5
py==1.6.0
py-cpuinfo==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pygame==2.3.0
pyglet==2.0.5
pyparsing==2.2.2
PySC2==3.0.0
pytest==4.3.1
python-dateutil==2.7.3
python-utils==3.5.2
PyYAML==5.3.1
requests==2.21.0
requests-oauthlib==1.3.1
rsa==4.9
rware==1.0.3
s2clientprotocol==4.10.1.75800.0
s2protocol==5.0.11.89720.0
sacred==0.8.2
scipy==1.7.3
six==1.11.0
sk-video==1.1.10
SMAC @ git+https://github.com/oxwhirl/smac.git@8a092e4bd0c6f5d3cf929523c67e1bca861463aa
smmap==5.0.0
snakeviz==2.1.1
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-logger==0.1.0
tensorboard-plugin-wit==1.8.1
torch==1.13.1+cu117
torchaudio==0.13.1+cu117
torchvision==0.14.1+cu117
tornado==5.1.1
typing_extensions==4.5.0
urllib3==1.23
websocket-client==0.53.0
Werkzeug==2.2.3
whichcraft==0.5.2
wrapt==1.10.11
zipp==3.15.0

**Comment by semitable** [comment]
Looks like you have changed the default configs. Could you try disabling tensorboard and running again?
I am not sure where you changed that value (maybe config/default.yaml?). But the default value is false afaik

**Comment by abdulghani91** [comment]
@semitable I already have a copy of the original configs I will replace them all and run it again with turn off the tensorboard.

**Comment by abdulghani91** [comment]
@semitable yes you were wright, I disable the tensorboard and its work. But I have a research and plotting the changes of each algorithm is important for me. How can I run the tensorboard or plot the curves, is there any other tools for that?

**Comment by FADEAWAY114** [comment]
python src/main.py --config=qmix --env-config=gymma with env_args.time_limit=500 env_args.key="rware:rware-tiny-2ag-v1"
When I execute the command, I get an error like this，can someone help me with this

[DEBUG 10:55:52] git.cmd Popen(['git', 'version'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=None)
[DEBUG 10:55:52] git.cmd Popen(['git', 'version'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=None)
[DEBUG 10:55:52] git.cmd Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=None)
[DEBUG 10:55:52] git.cmd Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=None)
[DEBUG 10:55:52] git.cmd Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=<valid stream>)
[DEBUG 10:55:52] git.cmd Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=None)
[DEBUG 10:55:52] git.cmd Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=None)
[DEBUG 10:55:52] git.cmd Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=<valid stream>)
[DEBUG 10:55:52] git.cmd Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=None)
[DEBUG 10:55:52] git.cmd Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=None)
[DEBUG 10:55:52] git.cmd Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Users\asus\epymarl, universal_newlines=False, shell=None, istream=<valid stream>)
src/main.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(v, collections.Mapping):
[INFO 10:55:53] root Saving to FileStorageObserver in results/sacred.
[DEBUG 10:55:54] pymarl Using capture mode "fd"
[INFO 10:55:54] pymarl Running command 'my_main'
--- Logging error ---
[INFO 10:55:54] pymarl Started run with ID "1"
--- Logging error ---
[DEBUG 10:55:54] pymarl Starting Heartbeat
--- Logging error ---
[DEBUG 10:55:54] my_main Started
--- Logging error ---
[WARNING 10:55:54] my_main CUDA flag use_cuda was switched OFF automatically because no CUDA devices are available!
--- Logging error ---
[INFO 10:55:54] my_main Experiment Parameters:
--- Logging error ---
[INFO 10:55:54] my_main

{   'action_selector': 'epsilon_greedy',
    'add_value_last_step': True,
    'agent': 'rnn',
    'agent_output_type': 'q',
    'batch_size': 32,
    'batch_size_run': 1,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '',
    'double_q': True,
    'env': 'gymma',
    'env_args': {   'key': 'rware-tiny-2ag-v1',
                    'pretrained_wrapper': None,
                    'seed': 356102410,
                    'time_limit': 500},
    'epsilon_anneal_time': 50000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'evaluation_epsilon': 0.0,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hidden_dim': 64,
    'hypergroup': None,
    'hypernet_embed': 64,
    'hypernet_layers': 2,
    'label': 'default_label',
    'learner': 'q_learner',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 50000,
    'lr': 0.0005,
    'mac': 'basic_mac',
    'mixer': 'qmix',
    'mixing_embed_dim': 32,
    'name': 'qmix',
    'obs_agent_id': True,
    'obs_individual_obs': False,
    'obs_last_action': False,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'render': False,
    'repeat_id': 1,
    'runner': 'episode',
    'runner_log_interval': 10000,
    'save_model': False,
    'save_model_interval': 50000,
    'save_replay': False,
    'seed': 356102410,
    'standardise_returns': False,
    'standardise_rewards': True,
    't_max': 2050000,
    'target_update_interval_or_tau': 200,
    'test_greedy': True,
    'test_interval': 50000,
    'test_nepisode': 100,
    'use_cuda': False,
    'use_rnn': False,
    'use_tensorboard': False}

--- Logging error ---
D:\Anaconda3-4.3.1\envs\parking\lib\site-packages\sacred\stdout_capturing.py:184: UserWarning: tee_stdout.wait timeout. Forcibly terminating.
  warnings.warn("tee_stdout.wait timeout. Forcibly terminating.")
[DEBUG 10:55:56] pymarl Stopping Heartbeat
[ERROR 10:55:56] pymarl Failed after 0:00:02!
Traceback (most recent calls WITHOUT Sacred internals):
  File "D:\Anaconda3-4.3.1\envs\parking\lib\site-packages\gym\envs\registration.py", line 158, in spec
    return self.env_specs[id]
KeyError: 'rware-tiny-2ag-v1'

During handling of the above exception, another exception occurred:

Traceback (most recent calls WITHOUT Sacred internals):
  File "src/main.py", line 36, in my_main
    run(_run, config, _log)
  File "C:\Users\asus\epymarl\src\run.py", line 55, in run
    run_sequential(args=args, logger=logger)
  File "C:\Users\asus\epymarl\src\run.py", line 87, in run_sequential
    runner = r_REGISTRY[args.runner](args=args, logger=logger)
  File "C:\Users\asus\epymarl\src\runners\episode_runner.py", line 15, in __init__
    self.env = env_REGISTRY[self.args.env](**self.args.env_args)
  File "C:\Users\asus\epymarl\src\envs\__init__.py", line 14, in env_fn
    return env(**kwargs)
  File "C:\Users\asus\epymarl\src\envs\__init__.py", line 82, in __init__
    self.original_env = gym.make(f"{key}", **kwargs)
  File "D:\Anaconda3-4.3.1\envs\parking\lib\site-packages\gym\envs\registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "D:\Anaconda3-4.3.1\envs\parking\lib\site-packages\gym\envs\registration.py", line 128, in make
    spec = self.spec(path)
  File "D:\Anaconda3-4.3.1\envs\parking\lib\site-packages\gym\envs\registration.py", line 203, in spec
    raise error.UnregisteredEnv("No registered env with id: {}".format(id))
gym.error.UnregisteredEnv: No registered env with id: rware-tiny-2ag-v1
