### ISSUE TITLE
Does this library support continuous action spaces?

### ISSUE THREAD

**Issue by 128f** [uoe-agents/epymarl#47]
I'm getting

```
AttributeError: 'Box' object has no attribute 'n'
```

When I try to use a `spaces.Tuple ( tuple ( spaces.box(` as an action space for a gym environment, and I suspect (from some of the issues on this repo, [some of the code](https://github.com/uoe-agents/epymarl/blob/main/src/envs/__init__.py#L150) and discussion elsewhere) that it is because this repo does not support continuous action spaces, is that right?

**Comment by cr0ax** [comment]
Update: I thought I saw some of the MPE code had the ability to have `Box` action spaces, but just from the [README](https://github.com/semitable/multiagent-particle-envs#multi-agent-particle-environment) it seems that is note the case.

The more I look investigate the `gymma` [environment](https://github.com/uoe-agents/epymarl/blob/main/src/envs/__init__.py) the more it seems like I can only use `Discrete` actions

**Comment by cr0ax** [comment]
yeah, that's what I thought
I'm holding out hope that maybe I can peel the softmax layer off somehow

**Comment by LukasSchaefer** [comment]
Hi! Sorry for the very late response.

Most algorithms implemented within EPyMARL would not be fit for continuous action spaces and we have unfortunately no plans to implement such integration, sorry. If you are looking for a MARL library that supports continuous action spaces, [BenchMARL](https://github.com/facebookresearch/BenchMARL) might be worth a look!

I will close the issue since we have no plans of implementing this.

On a sidenote, we just published a big update to EPyMARL including lots of new features (including training in non-common-reward games, move to gymnasium from deprecated gym, weights and biases logging) -- you can find more details in the readme!
