### ISSUE TITLE
How could I render the lbf environment?

### ISSUE THREAD

**Issue by issuey** [uoe-agents/epymarl#52]
When I set render=True to render the lbf environment, I met the following problem, is there anyone else had met the same problem before?
![image](https://github.com/uoe-agents/epymarl/assets/74280544/038a3b9c-4548-4ed9-a2b4-e76f0a4c5000)
How could I render the test result?

**Comment by LukasSchaefer** [comment]
Hi, sorry for the very late response.

It seems your issue is unrelated to EPyMARL but instead an issue with dependencies of the LBF environment (I believe due to the `pyglet` version). Please check the [LBF environment repo](https://github.com/semitable/lb-foraging) where we have recently pushed an update which should address your issue. If your issue is not addressed already, please raise an issue in that repository. Thanks!
