### ISSUE TITLE
Recommended torch version?

### ISSUE THREAD

**Issue by LXXXXR** [uoe-agents/epymarl#63]
Hi,

Thank you so much for this wonderful repo! But I was wondering could you advice on the recommended version of torch so that our first-time users will be able to use this repo more smoothly? That would be extremely helpful.

Thank you in advance!

**Comment by LukasSchaefer** [comment]
Hi!

First, sorry for the very late response. EPyMARL should be fairly agnostic to the underlying torch version. I have ran it with < 2.0 torch and most recently with torch 2.3.1.

On a sidenote, we just published a big update to EPyMARL including lots of new features (including training in non-common-reward games, move to gymnasium from deprecated gym, weights and biases logging)! This should make dependencies and installation easier due to the removal of the deprecated `gym` environment and separation of the installation of environments.

I will close the issue for now, but let us know if there are any outstanding issues!
