### ISSUE TITLE
Adding new environment to ePYMARL

### ISSUE THREAD

**Issue by ay-ka** [uoe-agents/epymarl#64]
Hello, 

I was wondering whether there are any instruction about adding new environments (compatible with gym interface) to this library?

**Comment by LukasSchaefer** [comment]
Hi! Thanks a lot for raising this.

We just published a big update to EPyMARL including lots of new features (including training in non-common-reward games, move to gymnasium from deprecated gym, weights and biases logging). As part of this, we also describe in the documentation [how to register and run experiments in own environments](https://github.com/uoe-agents/epymarl?tab=readme-ov-file#registering-and-running-experiments-in-custom-environments). Note that this uses the newly integration `gymnasium` library in replacement of the deprecated `gym` we previously used. If you'd like to integrate a new environment that is based on `gym`, I recommend to take a look at the compatibility wrappers of `gymnasium` here: https://gymnasium.farama.org/content/gym_compatibility/

I close this issue for now since there is new documentation on how to do this, but let us know if there are any outstanding issues!
