### ISSUE TITLE
Errors in search.py

### ISSUE THREAD

**Issue by opocaj92** [uoe-agents/epymarl#73]
Hi everyone,
While browsing through the files, I noticed that the file `search.py` has some errors:

1. On line 24, there is a call to `_get_ingredient_from_mask()`, which is not defined nor imported anywhere
2. On line 81 you are doing `from train import ex`, but there is no `train.py` nor such a library in the `env_requirements.txt` file

How could these errors be fixed? Hyper-params search is a very good contribution to this, so it is a shame that it is simply bugged...

**Comment by LukasSchaefer** [comment]
Hi! Thanks a lot for raising this.

These parts of the code were actually unused and, therefore, the script could still be used. Nevertheless, I just removed and updated the `search.py` script to make sure there are no such errors. I'll close this issue since it should be resolved. Let me know if there are any outstanding issues.

Also, we just published a big update to EPyMARL including lots of new features (including training in non-common-reward games, move to gymnasium from deprecated gym, weights and biases logging)!
